# orquestra os contêineres do servidor e dos clientes, 
# permitindo rodar múltiplos serviços de forma integrada.

version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"

  client1:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server

  client2:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server

  client3:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
  client4:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server





